// Fabricated Au Pair family listings used for the "Au Pair" job category.
// Generated the same way as src/lib/mock-data.ts (no live backend needed).
// Photos are hand-picked, individually verified Unsplash photo IDs (real
// photography, free to use under the Unsplash License) rather than
// hotlinked search-engine results or guessed URLs.

import type { AuPairPreferences, Employer, Job } from "@/lib/supabase/types";

interface AuPairSeed {
  id: string;
  familyName: string;
  countryFlag: string;
  country: string;
  city: string;
  children: number[];
  startWindow: string;
  duration: string;
  languages: string[];
  occupation: string;
  highlight: string;
  familyDescription: string;
  uniqueExperience: string;
  preferences: AuPairPreferences;
  images: string[];
  publishedAt: string;
  status: "published" | "closed";
  expiresAt?: string;
  verified: boolean;
}

const SEEDS: AuPairSeed[] = [
  {
    id: "iris",
    familyName: "Iris",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Woerden, NL",
    children: [2, 5],
    startWindow: "Sep - Oct 2026",
    duration: "6 - 24 months",
    languages: ["English"],
    occupation: "Speech therapy student and Manager",
    highlight: "Canal-side town near Utrecht",
    familyDescription:
      "Hello! We are a warm and welcoming family from the Netherlands looking for a kind and enthusiastic au pair to become part of our family. We have two wonderful boys, aged 2 and 5, who are curious, energetic, and love playing, exploring, and spending time outdoors. We are looking for someone who is reliable, caring, responsible, cheerful, and truly enjoys being around children. It would be wonderful if you are creative, enjoy going for walks, and like coming up with fun activities for young children. We hope to find someone who will feel like a big sister to our boys and enjoy being part of our daily family life. We live in a comfortable house with a large garden, where the children love to play. As our au pair, you will have your own private bedroom and share a bathroom with the children. We hope to welcome someone who enjoys family life, and is excited to experience Dutch culture while creating happy memories with us. We believe good communication, mutual respect, and kindness are the foundation of a great au pair experience. If this sounds like the right family for you, we would love to hear from you and get to know you better!\n\nLiving with our family means you can enjoy life in a small, friendly town with lots of green spaces and nature. It is a safe and peaceful place where you can feel at home. There is always something to do in the surrounding area. You can visit nearby cities, go shopping, enjoy cafés and restaurants, explore parks, go cycling, or take beautiful walks in nature. Public transport is good, making it easy to discover more of the Netherlands in your free time. As part of our family, you will have the chance to experience Dutch culture, improve your English or Dutch, and create wonderful memories while spending time with our children. We hope you will feel like a true member of our family and enjoy a fun and rewarding year with us.\n\nA Day in the Life of an Au Pair with Our Family. A typical day starts with helping the children (ages 2 and 5) get ready for the day and enjoying breakfast together. After breakfast, you will take our oldest child to school. Then you and our youngest can spend the morning together. You might go into town to do some grocery shopping, enjoy a walk, visit a playground, or play together at home. Around lunchtime, you'll have lunch with our youngest before heading to school to pick up our oldest child. Back at home, you can enjoy a drink and a snack together and spend some time playing or doing a fun activity. Later in the afternoon, you'll help prepare dinner. We enjoy eating together as a family whenever possible. After dinner, you'll help with the children's bedtime routine, such as getting them ready for bed, reading a story, and tucking them in. Once the children are asleep, you'll do some light tidying up related to the children. After that, the evening is yours to relax and enjoy your free time.\n\nWe are looking for a kind, calm, and enthusiastic au pair who enjoys spending time with young children. Someone who is independent, takes initiative, and is reliable is a great fit for our family. We appreciate an au pair who enjoys cooking simple meals and is happy to help with everyday family life. It is important to us that you are responsible, easy-going, and feel comfortable managing daily tasks on your own. Most of all, we hope to welcome someone who will become part of our family. We would love to spend time together, enjoy fun outings, share meals, and create wonderful memories during your stay with us.",
    uniqueExperience:
      "We live in a lovely town, close to the town centre and surrounded by beautiful green spaces and water. Our home is in a peaceful area where you can enjoy walks, cycling, and relaxing by the water, while still being close to shops, cafés, and everything you need. One of the best things about our location is that it is easy to travel by train to some of the Netherlands' biggest and most beautiful cities, such as Amsterdam, Utrecht, Rotterdam, and The Hague. This makes it easy to explore the country during your free time. As part of our family, you will experience everyday Dutch life and have the opportunity to improve your English and, if you like, learn some Dutch. We also enjoy doing fun activities together as a family, such as visiting playgrounds, going on day trips, exploring nature, and spending time outdoors. We hope you'll create wonderful memories with us while developing new skills and experiencing a new culture.",
    preferences: {
      gender: "Female au pair",
      ageRange: "18-31 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French", "German", "Italian", "Spanish"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1542037104857-ffbb0b9155fb?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581998392741-67879e0ef04a?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-18T09:14:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "van-dijk",
    familyName: "van Dijk",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Amsterdam, NL",
    children: [3, 6],
    startWindow: "Oct 2026",
    duration: "12 - 24 months",
    languages: ["English", "Dutch"],
    occupation: "Architect and Paediatrician",
    highlight: "Canal house, 5 min bike to the centre",
    familyDescription:
      "We're a busy, easy-going family in the heart of Amsterdam — Mark designs buildings, Sanne works long but flexible shifts at the children's hospital, and our two kids (3 and 6) keep the house loud and happy. We're looking for a patient, hands-on au pair who genuinely enjoys toddlers and school-run chaos in equal measure, and who won't mind the occasional early morning when Sanne is on call. Our home is a narrow canal house with a small roof terrace, a bike for every family member, and a fridge that's always stocked for pancake emergencies.\n\nMost days start with breakfast together before the school run — our six-year-old cycles with a parent, and our three-year-old goes to the crèche around the corner. Afternoons are yours to fill with playground trips, swimming lessons, or simply pottering around the neighbourhood. We eat dinner as a family whenever Sanne's shift allows, and we'd love an au pair who's curious about Dutch life, happy on two wheels, and ready to become a genuine part of our little household.",
    uniqueExperience:
      "Living with us means living in Amsterdam itself — canals, bridges, and bicycle bells outside the window every morning. Museums, markets, and parks are all a short ride away, and the international community here means you'll never feel far from home. Weekend trips to Haarlem, Utrecht, or the coast are easy by train, and our kids love showing visitors their favourite ice cream spot by the canal.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-30 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "Spanish", "Portuguese"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1717180436987-089b88a2d782?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1717753045265-fa6ab160384a?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1602255680702-c47261041a97?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-06-02T07:45:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "hoffmann",
    familyName: "Hoffmann",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Munich, DE",
    children: [4],
    startWindow: "Nov 2026 - Jan 2027",
    duration: "6 - 12 months",
    languages: ["English", "German"],
    occupation: "Software Engineer and Freelance Illustrator",
    highlight: "Weekend trips to the Alps",
    familyDescription:
      "We're a small, creative family of three in Munich — Jonas builds software for a mobility start-up, Lea illustrates children's books from her home studio, and our son Theo (4) is obsessed with dinosaurs and anything that lets him climb higher than he should. We're after a warm, playful au pair who's happy to get down on the floor and build entire dinosaur worlds out of cushions, and who can also handle a rainy-day museum trip without breaking a sweat.\n\nOur days are fairly relaxed: kindergarten drop-off in the morning, pick-up early afternoon, then park time, art projects at the kitchen table, or a walk along the Isar river. Lea works from home most days, so you'll never feel isolated — we'd love for you to feel like a genuine part of our little creative household, not just childcare on the side.",
    uniqueExperience:
      "Munich gives you the best of both worlds — a lively, walkable city with English widely spoken, and the Alps less than an hour away for weekend hikes or, come winter, your first ski lesson. We often take Theo up to the lakes south of the city, and we'd happily bring you along. Munich's beer gardens, English Garden, and easy train links to Salzburg and Innsbruck make weekends here hard to beat.",
    preferences: {
      gender: "Female au pair",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Spanish", "Italian", "French"],
      languageLevel: "English Intermediate, basic German a plus",
      food: "Vegetarian-friendly kitchen",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1665393717290-361bfe403e83?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559054109-82d938dac629?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-07-11T14:22:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "berger",
    familyName: "Berger",
    countryFlag: "🇦🇹",
    country: "Austria",
    city: "Salzburg, AT",
    children: [1],
    startWindow: "Immediately",
    duration: "9 - 12 months",
    languages: ["English", "German"],
    occupation: "Orchestra Musician and Hotel Manager",
    highlight: "Mountain village just outside the city",
    familyDescription:
      "We're first-time parents adjusting to life with our daughter Mila, who just turned one and has recently discovered the joy of pulling herself up on absolutely everything. Klara plays cello with the local orchestra and rehearses several evenings a week; Felix manages a small family-run hotel with long but flexible hours. We need a gentle, attentive au pair who's confident with babies and toddlers and comfortable taking the evening shift a few times a week.\n\nOur village sits just outside Salzburg, surrounded by farmland and mountains, in a big old house with more garden than we know what to do with. Days are unhurried — morning walks in the pram, naps, baby-led play, and trips into the city for groceries or a coffee. We'd love someone who's happy with a quieter pace of life and excited to watch a baby grow into a toddler over the year.",
    uniqueExperience:
      "You'll wake up to mountain views every morning and be twenty minutes from Salzburg's old town, with its music festivals, riverside walks, and Christmas markets in winter. The wider region opens up easily too — Munich, the Salzkammergut lakes, and the Alps are all within reach for day trips, and Felix can usually sort a good rate at partner hotels if you fancy a weekend away.",
    preferences: {
      gender: "Female au pair",
      ageRange: "20-30 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1603317581682-c3c3e3a3a588?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560707854-fb9a10eeaace?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1542948843-bf19f4f535cf?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-05-14T11:05:00Z",
    status: "published",
    verified: false,
  },
  {
    id: "dubois",
    familyName: "Dubois",
    countryFlag: "🇧🇪",
    country: "Belgium",
    city: "Ghent, BE",
    children: [5, 8],
    startWindow: "Sep 2026",
    duration: "12 months",
    languages: ["English", "French"],
    occupation: "Lawyer and Chef",
    highlight: "Medieval city centre, canal views",
    familyDescription:
      "We're a food-loving family in the middle of Ghent's old town — Camille practises corporate law, Étienne runs the kitchen at a small bistro (so evenings are his busiest time), and our two children, 5 and 8, already have very strong opinions about pasta shapes. We need an au pair who's organised enough to manage the after-school routine solo a few evenings a week, and who doesn't mind being roped into taste-testing whatever Étienne brings home.\n\nSchool drop-off is early, and afternoons are yours and the kids' — homework, the canal-side park, or swimming lessons on Wednesdays. We eat well and often, and we'd genuinely love for you to join us at the table most nights. Weekends usually mean a market trip or a bike ride along the canals, and we're happy to help you explore more of Belgium on your days off.",
    uniqueExperience:
      "Ghent is a smaller, quieter cousin of Bruges and Brussels — cobbled streets, canal boats, and a lively student population that keeps the city young. You're 30 minutes from Brussels, an hour from the coast, and Bruges and Antwerp are both easy day trips. Étienne's restaurant connections mean you'll eat very well, and Camille is always up for showing off her favourite hidden courtyard cafés.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Spanish", "Italian", "German"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1761839258803-21515f43190c?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1628191012047-e789922abfdf?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605713288610-00c1c630ca1e?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-06-25T16:38:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "keller",
    familyName: "Keller",
    countryFlag: "🇨🇭",
    country: "Switzerland",
    city: "Zurich, CH",
    children: [2, 4, 7],
    startWindow: "Jan - Feb 2027",
    duration: "12 - 18 months",
    languages: ["English", "German"],
    occupation: "Investment Banker and Yoga Instructor",
    highlight: "Lake Zurich swimming in summer",
    familyDescription:
      "We're a full, energetic household of five — Reto works long hours in banking, Nadine teaches yoga and manages our three whirlwind children (2, 4, and 7), and between school runs, naps, and gymnastics classes, there's rarely a quiet moment. We need a genuinely experienced au pair who's confident managing multiple ages at once and comfortable taking real ownership of the daily routine, especially on Nadine's teaching evenings.\n\nOur house is a short tram ride from the lake, with a garden the kids have thoroughly claimed as their own. A typical day involves school and kindergarten drop-offs, an afternoon of park time or swimming, and a wind-down before dinner that we try hard to eat together. It's a busy but warm home, and we're looking for someone who thrives on structure but still knows how to have fun.",
    uniqueExperience:
      "Zurich is famously easy to live in — clean, safe, and built around the lake, where locals swim straight from the grassy banks all summer. You're close to some of Europe's most spectacular scenery, with weekend trips to Lucerne, Interlaken, or the mountains all within a couple of hours by train. Nadine can also get you into her yoga studio for free classes on your days off.",
    preferences: {
      gender: "Female au pair",
      ageRange: "20-30 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French", "Italian"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1475503572774-15a45e5d60b9?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502143135356-dcdb8a9a3da6?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503431153573-96e959f4d9b7?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-04-09T08:52:00Z",
    status: "closed",
    expiresAt: "2026-07-05T23:59:00Z",
    verified: true,
  },
  {
    id: "de-groot",
    familyName: "de Groot",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Groningen, NL",
    children: [6],
    startWindow: "Sep 2026",
    duration: "6 - 12 months",
    languages: ["English", "Dutch"],
    occupation: "General Practitioner",
    highlight: "University town, cycling everywhere",
    familyDescription:
      "It's just me and my son Daan (6) — I'm a GP with a demanding but fairly predictable schedule, and Daan is sociable, sporty, and always up for an adventure, as long as it involves a football at some point. I'm looking for a reliable au pair who can genuinely become part of our small family, someone Daan can look up to and who I can trust completely on the afternoons I'm at the practice late.\n\nOur days are simple and routine-driven: school drop-off together in the morning, pick-up around 3pm, then homework, football practice, or just messing around in the garden until dinner. I try to keep evenings free for us as a family, so your evenings are usually your own. Groningen is a young, bike-friendly city, and I'd love an au pair who's happy to get around on two wheels and make the most of student-town life.",
    uniqueExperience:
      "Groningen is one of the youngest cities in Europe by population — a third of residents are students, which means a genuinely lively bar and café scene, cheap cinema nights, and a very welcoming international crowd. Everything is cyclable, the historic centre is beautiful, and Amsterdam is under two hours away by train if you want a bigger city fix.",
    preferences: {
      gender: "Any gender",
      ageRange: "18-27 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "Polish"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1610898764137-d44d5aa98af9?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1531984929664-2fb2be468d3e?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1607453998774-d533f65dac99?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-04T19:10:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "schmidt",
    familyName: "Schmidt",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Hamburg, DE",
    children: [3, 9],
    startWindow: "Oct - Nov 2026",
    duration: "12 months",
    languages: ["English", "German"],
    occupation: "Marine Engineer and Marketing Director",
    highlight: "Harbour city, ferries and ships",
    familyDescription:
      "We're a harbour-city family through and through — Finn works as a marine engineer and is occasionally away for a week at a time, Lotte leads a marketing team and juggles the school run around meetings, and our kids (3 and 9) love nothing more than watching the big container ships come into port. We need an au pair who can step up and hold the fort solo when Finn's away, and who's genuinely comfortable with both a toddler's nap schedule and a nine-year-old's homework demands.\n\nWe live in a quiet residential street a short ride from the harbour, and our weekends often involve a ferry trip, the fish market, or a walk along the Elbe. We eat dinner together most nights and try to keep the house calm even when the schedule isn't. If you love the water and don't mind the occasional grey, drizzly day, Hamburg has a lot to offer.",
    uniqueExperience:
      "Hamburg is a proper working port city with a green, leafy side too — the Alster lakes for picnics, the Speicherstadt warehouse district for exploring, and the famous fish market on Sunday mornings. It's well connected by train to Berlin, Copenhagen, and Amsterdam, so your days off can easily turn into weekend trips further afield.",
    preferences: {
      gender: "Female au pair",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Dutch", "Danish", "Swedish"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1606474226448-4aa808468efc?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560328055-e938bb2ed50a?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1524503033411-c9566986fc8f?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-07-29T06:30:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "peeters",
    familyName: "Peeters",
    countryFlag: "🇧🇪",
    country: "Belgium",
    city: "Antwerp, BE",
    children: [1, 4],
    startWindow: "Mar 2027",
    duration: "6 - 9 months",
    languages: ["English", "Dutch"],
    occupation: "Diamond Trader and Interior Designer",
    highlight: "Fashion & diamond district",
    familyDescription:
      "We're a design-minded family in central Antwerp — Bram trades in the diamond district, Elise runs a small interior design studio from home, and our two children (1 and 4) are equal parts curious and stubborn. We're looking for a warm, hands-on au pair who's genuinely comfortable with both a mobile toddler and a determined one-year-old, and who won't mind our house occasionally doubling as a mood-board showroom.\n\nOur apartment is bright, central, and close to everything — the zoo, the park, and a dozen good cafés within walking distance. Days usually involve a morning at the crèche and playgroup, an afternoon of errands or park time together, and a calm dinner before bed. Elise works from home most days, so it's a genuinely social household, not an empty one.",
    uniqueExperience:
      "Antwerp is stylish, walkable, and easy to love — a historic centre, a famous fashion scene, and a genuinely good food culture. Brussels is 45 minutes away, Ghent and Bruges are both close by train, and the Dutch border and Amsterdam aren't far either, so weekend trips are easy to plan.",
    preferences: {
      gender: "Female au pair",
      ageRange: "18-28 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French", "German"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1542385151-efd9000785a0?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1627764940620-90393d0e8c34?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1685580388390-576100ae9ce3?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-03-02T10:00:00Z",
    status: "closed",
    expiresAt: "2026-06-20T23:59:00Z",
    verified: false,
  },
  {
    id: "larsen",
    familyName: "Larsen",
    countryFlag: "🇩🇰",
    country: "Denmark",
    city: "Aarhus, DK",
    children: [5],
    startWindow: "Sep - Oct 2026",
    duration: "9 - 12 months",
    languages: ["English", "Danish"],
    occupation: "Veterinarian and Secondary School Teacher",
    highlight: "Beach 10 minutes by bike",
    familyDescription:
      "We're Mikkel and Anders, raising our daughter Freja (5) in a relaxed coastal suburb of Aarhus. Mikkel is a vet with early starts, Anders teaches at the local school with more predictable hours, and Freja is at that brilliant age where everything is a question and everything is an adventure. We need an au pair who's warm, patient, and genuinely enjoys the outdoors, because Freja rarely wants to stay inside for long.\n\nOur days follow the Danish rhythm of \"hygge\" — unhurried mornings, kindergarten drop-off, afternoons at the beach or in the garden, and cosy evenings together. We believe strongly in a calm, low-pressure home life, and we'd love someone who fits naturally into that pace rather than needing constant activity.",
    uniqueExperience:
      "Living here means sandy beaches, forest trails, and Denmark's famous cycling culture right outside the door. Aarhus itself is a compact, friendly city with a great café scene and an excellent aquarium Freja never tires of. Copenhagen is under three hours by train for a weekend if you want a bigger city fix.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "Norwegian", "Swedish"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1496275068113-fff8c90750d1?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1451471016731-e963a8588be8?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1592222491987-aebdb920e1a0?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-06-16T13:47:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "fischer",
    familyName: "Fischer",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Berlin, DE",
    children: [7, 10],
    startWindow: "Nov 2026",
    duration: "12 - 24 months",
    languages: ["English", "German"],
    occupation: "Civil Servant and Start-up Founder",
    highlight: "Vibrant capital city, parks everywhere",
    familyDescription:
      "We're a busy Berlin household — Petra works in city administration with steady hours, Tobias is building a start-up and keeps unpredictable ones, and our two kids (7 and 10) are old enough to be genuinely good company but still need a reliable adult around after school. We're looking for an independent, trustworthy au pair who's comfortable managing homework, hobbies, and the occasional last-minute schedule change.\n\nWe live in a leafy, family-friendly neighbourhood with a park at the end of the street. Afternoons usually mean music lessons, football training, or just hanging out, and we try to keep dinners together as a fixed point in an otherwise chaotic week. Berlin's size means there's always somewhere new to explore on your days off.",
    uniqueExperience:
      "Berlin is one of Europe's most international, creative cities — huge parks, an incredible museum scene, and a very easy place to make friends from all over the world. Our neighbourhood has excellent public transport, so you can be in the city centre in twenty minutes or out at a lake for a swim just as easily.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-30 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Spanish", "French", "Turkish"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1601909331597-c80bb4c948c2?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1614113036347-9f60df80730a?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1569870614214-04b2aef402c6?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-09T20:03:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "bakker",
    familyName: "Bakker",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Haarlem, NL",
    children: [3, 3],
    startWindow: "Oct 2026",
    duration: "12 months",
    languages: ["English", "Dutch"],
    occupation: "Florist and Primary School Teacher",
    highlight: "Tulip fields nearby in spring",
    familyDescription:
      "We're the very tired but very happy parents of twin boys, Jip and Sem (both 3), who together are exactly twice the energy you'd expect. Mila runs a small flower shop in town and Willem teaches at the local primary school, so our schedules are busy but fairly predictable. We need an au pair with genuine twin or multiples experience — or at least a lot of patience and a good sense of humour — who can handle two very different three-year-old personalities at once.\n\nOur house backs onto a shared courtyard garden where the boys play most afternoons with the neighbourhood kids. Mornings mean nursery drop-off, afternoons are pick-up and playtime, and dinner is a joyfully chaotic affair we hope you'll join most nights. In spring, the bulb fields nearby turn into an explosion of colour the boys never get tired of running through.",
    uniqueExperience:
      "Haarlem is a smaller, quieter alternative to Amsterdam (just 15 minutes away by train) with a beautiful old centre, a Saturday market, and the beach at Zandvoort only 20 minutes by bike. Spring here means the famous Dutch tulip fields are right on your doorstep — an unmissable experience if your placement lines up with the season.",
    preferences: {
      gender: "Female au pair",
      ageRange: "18-27 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "French"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1581546104075-e4ad519034bf?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1534982841079-afde227ada8f?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1647627611823-d08fa901678e?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-05-27T09:58:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "roth",
    familyName: "Roth",
    countryFlag: "🇨🇭",
    country: "Switzerland",
    city: "Bern, CH",
    children: [6],
    startWindow: "Jan 2027",
    duration: "12 months",
    languages: ["English", "German", "French"],
    occupation: "Diplomat and Physiotherapist",
    highlight: "Historic old town, river swimming",
    familyDescription:
      "We're a small, well-travelled family — Anja works for an international organisation and travels several times a year, Matthias runs his own physiotherapy practice with fairly fixed hours, and our son Elia (6) has already picked up bits of three languages just from being around us. We're looking for a confident, independent au pair who can take real responsibility when Anja is travelling, and who's excited to be part of a genuinely multilingual household.\n\nBern's old town is famously beautiful, and our apartment is a short walk from the river where locals swim and float downstream all summer. Elia's school day ends early, so afternoons are yours to fill with the aquatic centre, the Bear Park, or simply the river. We try to eat together every evening Matthias is home, and we love introducing an au pair to Swiss traditions along the way.",
    uniqueExperience:
      "Bern is compact, walkable, and stunning — a UNESCO old town, river swimming in summer, and mountains visible on a clear day. Geneva, Zurich, and the Alps are all within easy train reach, and Anja's diplomatic circle means occasional invites to genuinely interesting events and receptions.",
    preferences: {
      gender: "Female au pair",
      ageRange: "20-30 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Italian", "Spanish"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1656177999031-0d3e8e62317a?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1560707857-b897819e06fb?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1644941002474-6ee8ab0ee8cb?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-14T15:20:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "jansen",
    familyName: "Jansen",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Maastricht, NL",
    children: [4, 8],
    startWindow: "Sep 2026",
    duration: "12 - 18 months",
    languages: ["English", "Dutch"],
    occupation: "Surgeon and Psychologist",
    highlight: "Border town near Belgium & Germany",
    familyDescription:
      "We're a busy medical family in the south of the Netherlands — Iris operates several days a week with long, hard-to-predict hours, Bram runs his own psychology practice with more flexibility, and our two kids (4 and 8) are used to a household that runs on a shared calendar. We need a genuinely reliable au pair who's comfortable being the steady presence on Iris's theatre days, and confident managing two different school schedules.\n\nWe live in a quiet street a short walk from Maastricht's old town, with a garden the kids use constantly in good weather. Afternoons mean school pick-up, homework, and swimming or gymnastics depending on the day. We eat together whenever Iris's schedule allows, and we're a genuinely warm, close family who'd love an au pair who wants to feel part of that.",
    uniqueExperience:
      "Maastricht sits right where the Netherlands, Belgium, and Germany meet — you can cycle to another country for lunch. The city itself is one of the prettiest in the Netherlands, with a lively student population, great markets, and an easy day trip to Liège, Aachen, or Cologne whenever you fancy a change of scenery.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "French"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1742522450616-a2cf0cba1274?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1533222481259-ce20eda1e20b?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1502781252888-9143ba7f074e?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-07-06T05:59:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "wagner",
    familyName: "Wagner",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Cologne, DE",
    children: [1],
    startWindow: "Dec 2026 - Jan 2027",
    duration: "6 - 12 months",
    languages: ["English", "German"],
    occupation: "Architect and Radiologist",
    highlight: "Cathedral city on the Rhine",
    familyDescription:
      "We're brand-new parents finding our feet with our son Paul, who just turned one and has recently mastered the art of climbing out of everything we thought was climb-proof. Julia works as a radiologist with rotating shifts, Simon runs his own small architecture studio, and between us we're looking for an au pair who is genuinely confident with babies and comfortable with a schedule that shifts week to week.\n\nWe live in a bright apartment near the Rhine, a short walk from the cathedral and the old town. Days revolve around Paul's naps, walks along the river, and baby groups, and we'd love someone patient and affectionate who's excited to watch him grow through his first big year of milestones.",
    uniqueExperience:
      "Cologne is lively, riverside, and famously friendly, with the cathedral as your constant landmark. There's a strong international community, excellent public transport, and Düsseldorf, Bonn, and even Amsterdam are all within easy reach for a weekend away.",
    preferences: {
      gender: "Female au pair",
      ageRange: "19-28 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Dutch", "French"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1582486225644-aeacf6aa0b1b?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1557176278-3326a3193580?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1638202948587-ac48463ddb1f?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-01T12:15:00Z",
    status: "published",
    verified: false,
  },
  {
    id: "lambert",
    familyName: "Lambert",
    countryFlag: "🇱🇺",
    country: "Luxembourg",
    city: "Luxembourg City, LU",
    children: [3, 6],
    startWindow: "Sep - Oct 2026",
    duration: "12 months",
    languages: ["English", "French", "German"],
    occupation: "EU Institution Economist and Translator",
    highlight: "Trilingual household, castle day trips",
    familyDescription:
      "We're a proudly multilingual family — Sophie works for an EU institution, Antoine translates for a living, and our two children (3 and 6) are already switching between French, German, and a bit of Luxembourgish without thinking twice. We need an au pair who's comfortable in a household where three languages fly around the dinner table, and who's happy to add English into that mix consistently for the kids.\n\nOur home is a short tram ride from the old town, with a small garden and a very international street of neighbours. Days mean school drop-off, afternoon activities (usually music or swimming), and a calm family dinner most evenings. We travel often for work and would love an au pair who can hold things together confidently when one of us is away.",
    uniqueExperience:
      "Luxembourg City is small, green, and dramatically set among old fortifications and river gorges — genuinely one of Europe's most underrated capitals. Its central location means Brussels, Paris, and Trier's Roman ruins are all easy day or weekend trips, and the country's countryside of castles and vineyards is right on your doorstep.",
    preferences: {
      gender: "Female au pair",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Spanish", "Italian", "Portuguese"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1509924603848-aca5e5f276d7?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1655009316723-e4af5fe7afe1?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517554558809-9b4971b38f39?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-19T08:41:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "visser",
    familyName: "Visser",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Zandvoort, NL",
    children: [5, 9],
    startWindow: "Jun 2027",
    duration: "2 - 4 months (summer)",
    languages: ["English", "Dutch"],
    occupation: "Surf School Owner and Nurse",
    highlight: "Beachfront town",
    familyDescription:
      "We're a beach-town family through and through — Daan runs a small surf school right on the sand, Fem works shifts as a nurse, and our two kids (5 and 9) can practically swim before they can read. We're looking for an energetic, water-confident au pair for the summer season, someone who'll happily spend afternoons at the beach and doesn't mind sand tracked through the house on a daily basis.\n\nSummers here are full but relaxed — beach mornings, ice cream, and Daan's surf school buzzing with tourists. We eat outside most evenings, and the kids would love an au pair who's up for learning to surf alongside them. It's a seasonal, high-energy household, and a brilliant placement if you love the coast.",
    uniqueExperience:
      "Zandvoort is the Netherlands' liveliest seaside town, 30 minutes from Amsterdam by train, with a long sandy beach, beach clubs, and a genuine surf culture that's unusual for the Netherlands. Free surf lessons from Daan's school and easy access to Amsterdam and Haarlem make this a fantastic summer placement.",
    preferences: {
      gender: "Any gender",
      ageRange: "18-27 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "Danish"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1506456331400-7088248a8db1?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1597524678053-5e6fef52d8a3?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1626736608558-174e8dfa2aa6?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-20T17:26:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "braun",
    familyName: "Braun",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Freiburg, DE",
    children: [2, 4],
    startWindow: "Oct 2026",
    duration: "12 months",
    languages: ["English", "German"],
    occupation: "University Lecturers",
    highlight: "Black Forest hiking trails",
    familyDescription:
      "We're both academics at the university — Katharina lectures in environmental science, Paul in linguistics — and between lectures, research trips, and our two little ones (2 and 4), our week is a genuine juggling act. We need a calm, capable au pair who's comfortable holding the fort during a busy teaching week, and who enjoys outdoor time as much as our kids do.\n\nWe live in a quiet, green suburb with the Black Forest practically starting at our garden fence. Mornings mean kindergarten and crèche drop-off, afternoons are forest walks, playgrounds, or just muddy boots in the garden, and evenings are (usually) calm. We're a relaxed, low-pressure household that values fresh air over screen time.",
    uniqueExperience:
      "Freiburg is one of Germany's sunniest, greenest cities, right at the edge of the Black Forest with hiking and cycling trails starting minutes from home. It's also close to the French and Swiss borders, so Strasbourg and Basel are both easy day trips, and vineyard villages surround the city on every side.",
    preferences: {
      gender: "Female au pair",
      ageRange: "19-28 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French"],
      languageLevel: "English Intermediate",
      food: "Vegetarian household",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1534396708547-d8e912eb38ba?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1665393717338-dd07628bf667?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1555791019-72d3af01da82?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-06-30T09:33:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "claes",
    familyName: "Claes",
    countryFlag: "🇧🇪",
    country: "Belgium",
    city: "Bruges, BE",
    children: [7],
    startWindow: "Sep 2026",
    duration: "9 - 12 months",
    languages: ["English", "Dutch"],
    occupation: "Chocolatier",
    highlight: "Fairy-tale canal city",
    familyDescription:
      "It's just me and my son Louis (7) — I run a small chocolate shop in the historic centre, which means early starts and the occasional long Saturday when tourist season is at its peak. Louis is chatty, independent for his age, and absolutely will not say no to being your taste-tester if you're ever baking. I'm looking for a dependable au pair who can manage the after-school routine confidently and doesn't mind the shop's unpredictable seasonal hours.\n\nWe live above the shop in the middle of Bruges' postcard-perfect old town — cobblestones, canals, and swans included. Afternoons mean homework at the kitchen table, a walk along the canals, or the park just outside the centre. Evenings are usually ours together, and I try to keep weekends light so Louis gets proper family time.",
    uniqueExperience:
      "Bruges is one of Europe's best-preserved medieval cities — genuinely like stepping into a fairy tale, with canals, cobbled squares, and Christmas markets that draw visitors from across the world. Brussels and Ghent are both under an hour away, and the Belgian coast is a short train ride if you fancy the sea.",
    preferences: {
      gender: "Any gender",
      ageRange: "18-28 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French", "German"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1605812830455-2fadc55bc4ba?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1761839258568-fd466a93f68b?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1760084836111-b384c6d32104?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-02-19T09:00:00Z",
    status: "closed",
    expiresAt: "2026-05-31T23:59:00Z",
    verified: true,
  },
  {
    id: "novak",
    familyName: "Novak",
    countryFlag: "🇦🇹",
    country: "Austria",
    city: "Vienna, AT",
    children: [3, 5, 8],
    startWindow: "Nov 2026",
    duration: "12 - 24 months",
    languages: ["English", "German"],
    occupation: "Orchestra Conductor and Paediatric Nurse",
    highlight: "Imperial city, parks and palaces",
    familyDescription:
      "We're a full house of five in Vienna — Karl conducts for a chamber orchestra with an unpredictable rehearsal and touring schedule, Marta works shifts as a paediatric nurse, and our three children (3, 5, and 8) keep the house delightfully loud. We need a genuinely experienced au pair who can manage multiple ages and step confidently into a full evening solo when both of us are working.\n\nWe live near one of Vienna's grand parks, and our afternoons usually mean a mix of music practice, playground time, and homework for the eldest. We value good manners, calm routines, and a real love of classical music (though it's not required — our eldest will happily convert you). Dinners together are a fixed, non-negotiable part of our day whenever possible.",
    uniqueExperience:
      "Vienna is elegant, historic, and endlessly walkable — palaces, parks, and world-class music on every corner. Karl's orchestra connections mean occasional concert tickets, and the city's central location makes Budapest, Bratislava, and Salzburg all realistic weekend trips by train.",
    preferences: {
      gender: "Female au pair",
      ageRange: "20-30 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Italian", "Hungarian", "Czech"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1527490087278-9c75be0b8052?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1559225306-3f60aa7b39a3?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-07-22T18:12:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "meyer",
    familyName: "Meyer",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Stuttgart, DE",
    children: [6],
    startWindow: "Sep - Oct 2026",
    duration: "9 - 12 months",
    languages: ["English", "German"],
    occupation: "Automotive Engineer and Wellness Coach",
    highlight: "Vineyard hills surrounding the city",
    familyDescription:
      "We're a fairly relaxed family of three — Jonas is an automotive engineer with regular hours, Nina runs wellness workshops a few days a week, and our daughter Emma (6) is sporty, sociable, and always the last one out of the swimming pool. We're looking for an au pair who's active, patient, and happy to help Emma with her (extremely enthusiastic) gymnastics practice.\n\nOur house sits on the edge of the city with vineyard hills right behind it — a genuinely unusual setting for a state capital. Afternoons after school mean gymnastics, the garden, or a walk through the vines, and we eat dinner together most nights. It's a calm, structured household that values the outdoors over screen time.",
    uniqueExperience:
      "Stuttgart is greener and hillier than most people expect, ringed by vineyards that turn gold in autumn. It's a major hub for car culture (Nina jokes Jonas has museum privileges at two of them), and Munich, the Black Forest, and Lake Constance are all within easy weekend reach.",
    preferences: {
      gender: "Female au pair",
      ageRange: "18-28 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French", "Spanish"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1616337866123-ea967bfd7837?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1621354598022-16599af1b8b2?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1623249288685-835abe0123b4?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-05-05T07:18:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "smit",
    familyName: "Smit",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Leiden, NL",
    children: [2, 6],
    startWindow: "Sep 2026",
    duration: "12 months",
    languages: ["English", "Dutch"],
    occupation: "University Researcher and Data Scientist",
    highlight: "Historic university town",
    familyDescription:
      "We're a pair of academics-turned-parents — Eva researches at the university, Tim works as a data scientist mostly from home, and our two kids (2 and 6) are equally obsessed with picture books and mud puddles. We're looking for a curious, engaged au pair who enjoys reading with young children as much as running around after them, since Eva is determined to raise two little bookworms.\n\nTim's flexible schedule means the house is rarely empty, but we still need consistent help through school and crèche hours. Afternoons usually mean the park by the canal, a library visit, or simply pottering around our narrow, book-filled house. We're a quiet, thoughtful family who'd love an au pair who fits that same easy-going energy.",
    uniqueExperience:
      "Leiden is one of the Netherlands' prettiest towns — canals, historic university buildings, and windmills within the city itself. It's 15 minutes from The Hague, 35 from Amsterdam, and close enough to the coast for a beach afternoon whenever the weather allows.",
    preferences: {
      gender: "Any gender",
      ageRange: "18-28 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "French"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1715602109442-644d0f79d655?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1601193708180-afe6737e5636?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1770261431829-919301b84de3?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-16T10:47:00Z",
    status: "published",
    verified: false,
  },
  {
    id: "dupont",
    familyName: "Dupont",
    countryFlag: "🇧🇪",
    country: "Belgium",
    city: "Namur, BE",
    children: [4],
    startWindow: "Aug 2026",
    duration: "6 - 12 months",
    languages: ["English", "French"],
    occupation: "Craft Brewer and Teacher",
    highlight: "Countryside near the Ardennes forest",
    familyDescription:
      "We run a small family brewery just outside Namur — Julien handles the brewing, Camille teaches at the village school — and our daughter Louise (4) has grown up between mash tuns and a very large garden. We're looking for a hands-on, countryside-loving au pair who's happy with a slower pace of life and doesn't mind muddy boots by the back door.\n\nOur days are shaped by the seasons of the brewery as much as the school calendar — brewing days mean Julien is tied up from early morning, so we need someone confident handling Louise solo through the afternoon. We eat together most evenings, often with whoever's visiting the brewery that week, and weekends usually mean forest walks in the nearby Ardennes.",
    uniqueExperience:
      "Living near Namur means genuine Belgian countryside — the Ardennes forest for hiking, kayaking on the Meuse river in summer, and Namur's own hilltop citadel to explore. Brussels is under an hour by train, and the brewery itself is a fun, unusual place to spend your afternoons.",
    preferences: {
      gender: "Any gender",
      ageRange: "18-27 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Dutch", "German"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1761839258075-585182da7521?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1782212790904-5b658b182ffc?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1597413545419-4013431dbfec?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-03-27T13:29:00Z",
    status: "published",
    verified: false,
  },
  {
    id: "richter",
    familyName: "Richter",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Dresden, DE",
    children: [5, 9],
    startWindow: "Jan 2027",
    duration: "12 months",
    languages: ["English", "German"],
    occupation: "Art Restorer and Structural Engineer",
    highlight: "Baroque old town on the Elbe",
    familyDescription:
      "We're a creative-meets-technical household — Clara restores paintings for a regional museum, Ben is a structural engineer, and our two kids (5 and 9) split their time evenly between art projects and Lego engineering. We need an au pair who's genuinely happy either painting at the kitchen table or building something ambitious out of blocks, since both are daily occurrences here.\n\nWe live a short tram ride from Dresden's beautifully restored old town, along the river Elbe. Afternoons usually mean homework, a museum visit (we get in free thanks to Clara), or a walk along the riverside meadows. We eat together most evenings and love introducing an au pair to the city's quieter, less-touristed side.",
    uniqueExperience:
      "Dresden's old town is a genuine baroque masterpiece, rebuilt stone by stone after the war, sitting right on the Elbe river with meadows and cycling paths along the banks. Prague and Berlin are both under two hours away by train, making weekend trips very easy.",
    preferences: {
      gender: "Female au pair",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Czech", "Polish"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1531983412531-1f49a365ffed?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541692641319-981cc79ee10a?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-06-11T21:04:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "vermeer",
    familyName: "Vermeer",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Delft, NL",
    children: [3],
    startWindow: "Oct 2026",
    duration: "9 - 12 months",
    languages: ["English", "Dutch"],
    occupation: "Ceramic Artist and Civil Engineer",
    highlight: "Picture-postcard canal town",
    familyDescription:
      "We're a small family in the middle of Delft's old town — Anne makes traditional Delft Blue pottery in a studio behind our house, Sander works as a civil engineer, and our daughter Fenna (3) already has paint on her hands more often than not. We're after a creative, gentle au pair who's happy doing craft projects with a toddler and comfortable in a house where the studio door is basically always open.\n\nOur canal-side home is small but full of character, with Fenna's crèche just a five-minute walk away. Afternoons usually mean a visit to Anne's studio, a walk along the canals, or the market square when there's something happening. We eat together most evenings, and we'd love an au pair who's excited by Dutch craft and history as much as our daughter is.",
    uniqueExperience:
      "Delft is one of the most photogenic towns in the Netherlands — canals, a market square, and the university giving it a young, lively edge. The Hague and Rotterdam are both 15 minutes away by train, and Amsterdam is an easy day trip whenever you fancy a bigger city.",
    preferences: {
      gender: "Female au pair",
      ageRange: "18-27 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "French"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1501686637-b7aa9c48a882?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1514925312285-7a2c94c2c095?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1603367563698-67012943fd67?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-13T11:36:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "egger",
    familyName: "Egger",
    countryFlag: "🇨🇭",
    country: "Switzerland",
    city: "Lucerne, CH",
    children: [4, 7],
    startWindow: "Sep 2026",
    duration: "12 months",
    languages: ["English", "German"],
    occupation: "Mountain Guide and Physiotherapist",
    highlight: "Lake Lucerne and the Alps",
    familyDescription:
      "We're an outdoorsy family through and through — Reto guides hiking and ski tours for a living, Sina runs her own physiotherapy clinic, and our two kids (4 and 7) have basically grown up on trails and in a kayak. We need an active, confident-outdoors au pair who's genuinely happy hiking with the kids, not just supervising them from a bench.\n\nOur home looks out over Lake Lucerne, with mountains rising right behind it. Afternoons usually mean the lakeshore, a short hike, or ski lessons in winter. Reto's work sometimes takes him away for a night or two with clients, so we need someone we can rely on completely when that happens.",
    uniqueExperience:
      "Lucerne is postcard Switzerland — a lake, snow-capped peaks, and a beautifully preserved old town, all within walking distance of each other. Reto can often arrange discounted lift passes, and Zurich, Interlaken, and the Italian border are all realistic day trips.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["Italian", "French"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1783407290434-f8c66397fdd3?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1622498137457-1eb887d9147d?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1610194978275-8eee57ceafdd?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-07-17T06:52:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "thomsen",
    familyName: "Thomsen",
    countryFlag: "🇩🇰",
    country: "Denmark",
    city: "Copenhagen, DK",
    children: [2, 5],
    startWindow: "Nov 2026 - Jan 2027",
    duration: "12 months",
    languages: ["English", "Danish"],
    occupation: "Architects",
    highlight: "Cycling capital of the world",
    familyDescription:
      "We're Sofie and Line, both architects, raising our two children (2 and 5) in a design-conscious but happily messy home. Between client meetings and site visits, our schedules shift week to week, so we need an au pair who's flexible, organised, and comfortable holding things together without a fixed script. Our eldest is into everything Lego; our youngest is into everything else.\n\nCopenhagen life revolves around bikes — we cycle everywhere, rain or shine, and we'd love an au pair who's happy to do the same with a cargo bike full of kids. Afternoons mean kindergarten pick-up, playgrounds, or a harbour swim in summer. We value calm, unhurried family time and try hard to protect it from work.",
    uniqueExperience:
      "Copenhagen is consistently ranked one of the world's most liveable cities — safe, green, and built entirely around the bicycle. Harbour baths, world-class design, and an easy train connection to Malmö in Sweden make it an exceptional base for a placement.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German", "Swedish"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1681295695033-9c40d6586845?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1673890686673-005b85b14e53?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1620420678517-d45e226dfe6c?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-06T14:59:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "hendricks",
    familyName: "Hendricks",
    countryFlag: "🇳🇱",
    country: "Netherlands",
    city: "Eindhoven, NL",
    children: [6, 10],
    startWindow: "Sep 2026",
    duration: "12 - 24 months",
    languages: ["English", "Dutch"],
    occupation: "Tech Engineer and HR Manager",
    highlight: "Tech city with green parks",
    familyDescription:
      "We're a tech-industry family — Rens builds hardware for a major electronics company, Lieke leads HR for a similar-sized firm, and our two kids (6 and 10) are already better with a tablet than either of us. We're looking for an au pair who can encourage a healthy balance of screen time and outdoor play, and who's comfortable with two very different school-age routines.\n\nOur neighbourhood is quiet and green despite the city's tech-hub reputation, with a park at the end of the road. Afternoons mean homework, sports club, or just free play outside, and dinner together is a fixed part of our day whenever work allows. We're a warm, structured household that values curiosity and independence in equal measure.",
    uniqueExperience:
      "Eindhoven is one of Europe's most innovative small cities, but it's also unexpectedly green, with parks and cycling routes throughout. It's close to the Belgian border, so Antwerp and Brussels are both easy day trips, and the city's famous light festival in autumn is worth staying around for.",
    preferences: {
      gender: "Any gender",
      ageRange: "19-29 years old",
      region: "Schengen (EU & EEA)",
      languages: ["German"],
      languageLevel: "English Fluent",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1601294281485-2b5a214689dc?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1564156280315-1d42b4651629?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1607211851821-8be3cd6146f0?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-11T09:07:00Z",
    status: "published",
    verified: true,
  },
  {
    id: "graf",
    familyName: "Graf",
    countryFlag: "🇩🇪",
    country: "Germany",
    city: "Nuremberg, DE",
    children: [3],
    startWindow: "Sep - Oct 2026",
    duration: "9 - 12 months",
    languages: ["English", "German"],
    occupation: "Toy Designer and Kindergarten Teacher",
    highlight: "Medieval old town, Christmas market city",
    familyDescription:
      "We're a playful pair — Max designs toys for a well-known German toy company (our house is basically a prototype showroom), Hannah teaches kindergarten, and our son Felix (3) is, unsurprisingly, extremely well supplied with things to play with. We're looking for an imaginative, energetic au pair who's happy building elaborate pretend worlds and doesn't mind a living room that occasionally looks like a toy warehouse.\n\nOur home is close to Nuremberg's medieval old town, and Felix's crèche is a short walk away. Afternoons usually mean the castle grounds, a playground, or testing whatever prototype Max brought home that week. We eat together most evenings and love watching Felix's imagination take off with a new playmate around.",
    uniqueExperience:
      "Nuremberg's old town is one of Germany's most atmospheric, especially in December when the famous Christkindlesmarkt takes over the main square. Munich and Frankfurt are both under two hours away, and the surrounding Franconia region is full of castle towns worth a day trip.",
    preferences: {
      gender: "Any gender",
      ageRange: "18-27 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French", "Spanish"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1440288736878-766bd5839edb?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1541335370584-dc83f3ad05b1?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1628191013647-5640e14ded54?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-06-22T08:00:00Z",
    status: "published",
    verified: false,
  },
  {
    id: "boone",
    familyName: "Boone",
    countryFlag: "🇧🇪",
    country: "Belgium",
    city: "Leuven, BE",
    children: [1, 4],
    startWindow: "Oct 2026",
    duration: "12 months",
    languages: ["English", "Dutch"],
    occupation: "University Professor and Craft Brewer",
    highlight: "Historic university town near Brussels",
    familyDescription:
      "We're an academic-and-brewer pairing — Hannelore lectures at the university, Wout runs a small craft brewery with a taproom nearby, and our two children (1 and 4) split their days between lecture-hall visits and taproom afternoons (soft drinks only, of course). We're looking for a calm, capable au pair who's comfortable with a toddler and a baby together, and happy to be flexible around Wout's brewing schedule.\n\nOur house is a short walk from Leuven's beautiful old town and university buildings. Mornings mean crèche and playgroup drop-offs, afternoons are park time or a visit to the brewery garden, and we eat dinner together most nights once the little ones are settled. It's a lively, student-town atmosphere with a genuinely family-friendly pace.",
    uniqueExperience:
      "Leuven is one of Belgium's liveliest small cities, with a huge student population, a stunning Gothic town hall, and Brussels just 25 minutes away by train. Wout's brewery connections mean you'll get the inside track on Belgium's beer culture, non-alcoholic options included for the au pair on duty.",
    preferences: {
      gender: "Female au pair",
      ageRange: "18-28 years old",
      region: "Schengen (EU & EEA)",
      languages: ["French", "German"],
      languageLevel: "English Intermediate",
      food: "All Foods",
      smoking: "No smoking",
    },
    images: [
      "https://images.unsplash.com/photo-1628191011227-522c7c3f0af9?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1539920951450-2b2d59cff66d?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1554200991-de2527940354?w=1200&q=80&auto=format&fit=crop",
    ],
    publishedAt: "2026-08-21T07:30:00Z",
    status: "published",
    verified: true,
  },
];

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export const auPairEmployers: Employer[] = SEEDS.map((seed, i) => ({
  id: `emp-aupair-${i + 1}`,
  profile_id: `profile-emp-aupair-${i + 1}`,
  company_name: `Family ${seed.familyName}`,
  company_registration_number: null,
  industry: "Au Pair Placement",
  website: null,
  company_size: null,
  about: null,
  is_verified: seed.verified,
  created_at: seed.publishedAt,
  updated_at: seed.publishedAt,
}));

export const auPairJobs: Job[] = SEEDS.map((seed, i) => {
  const childLabel = seed.children.length === 1 ? "1 Child" : `${seed.children.length} Children`;
  const images = seed.images;

  return {
    id: `job-aupair-${i + 1}`,
    employer_id: `emp-aupair-${i + 1}`,
    title: `Au Pair for ${childLabel} — Family ${seed.familyName}, ${seed.country}`,
    slug: `au-pair-family-${slugify(seed.familyName)}-${slugify(seed.city.split(",")[0])}`,
    category: "au_pair",
    employment_type: "full_time",
    location: seed.city,
    is_remote: false,
    visa_sponsorship: false,
    description: seed.familyDescription.split("\n\n")[0],
    requirements: null,
    benefits: null,
    status: seed.status,
    published_at: seed.publishedAt,
    expires_at: seed.expiresAt ?? null,
    created_at: seed.publishedAt,
    updated_at: seed.expiresAt ?? seed.publishedAt,
    auPair: {
      familyName: seed.familyName,
      countryFlag: seed.countryFlag,
      country: seed.country,
      children: seed.children,
      startWindow: seed.startWindow,
      duration: seed.duration,
      languages: seed.languages,
      occupation: seed.occupation,
      highlight: seed.highlight,
      familyDescription: seed.familyDescription,
      uniqueExperience: seed.uniqueExperience,
      preferences: seed.preferences,
      images,
    },
  };
});
